#!/bin/bash

echo "🚀 Adding more journeys to the database..."
echo ""
echo "Please run the following SQL in your Supabase SQL Editor:"
echo "=================================================="
echo ""
cat supabase/seed/add-more-journeys.sql
echo ""
echo "=================================================="
echo ""
echo "Steps:"
echo "1. Go to https://supabase.com/dashboard"
echo "2. Select your project"
echo "3. Navigate to SQL Editor"
echo "4. Click 'New Query'"
echo "5. Copy and paste the SQL above"
echo "6. Click 'Run'"
echo ""
echo "This will add 14 new journeys for a total of 17 rotating journeys!"