// New places marked with Y that need to be added to amit-real-visited-places.ts

export const NEW_APPROVED_PLACES = [
  // From code references marked Y
  { name: "Toit Brewpub", notes: "I BEEN THERE", category: "bar" },
  { name: "Phoenix MarketCity", notes: "Shopping mall", category: "shopping" },
  { name: "Cubbon Park", notes: "Park for walks", category: "park" },
  { name: "Commercial Street", notes: "Shopping street", category: "shopping" },
  { name: "Vidhana Soudha", notes: "Government building", category: "landmark" },
  { name: "Third Wave Coffee", notes: "Coffee place", category: "cafe" },
  { name: "Corner House Ice Cream", notes: "Ice cream place", category: "dessert" },
  
  // From database marked Y
  { name: "99 Variety Dosa", notes: "VARIOUS PLACES IN BANGALORE", category: "restaurant" },
  { name: "Bangalore Club", notes: "Members club", category: "club" },
  { name: "Bangalore Fort", notes: "Historical fort", category: "landmark" },
  { name: "Bangalore Golf Club", notes: "Golf club", category: "club" },
  { name: "Bangalore Palace", notes: "Palace", category: "landmark" },
  { name: "Bannerghatta National Park", notes: "National park", category: "park" },
  { name: "Blossom Book House", notes: "Book store", category: "shopping" },
  { name: "Blue Tokai Coffee Roasters", notes: "Coffee roasters", category: "cafe" },
  { name: "Brahmin's Coffee Bar", notes: "Traditional coffee", category: "cafe" },
  { name: "Brigade Road", notes: "Shopping street", category: "shopping" },
  { name: "Byg Brewski Brewing Company", notes: "Brewery", category: "bar" },
  { name: "Cafe Coffee Day - MG Road", notes: "CCD outlet", category: "cafe" },
  { name: "CTR (Central Tiffin Room)", notes: "Same as CTR", category: "restaurant" },
  { name: "Defence Colony Park", notes: "Park", category: "park" },
  { name: "Ebony", notes: "Restaurant", category: "restaurant" },
  { name: "Empire Restaurant", notes: "Biryani place", category: "restaurant" },
  { name: "Fenny's Lounge", notes: "Lounge bar", category: "bar" },
  { name: "Forum Mall", notes: "Shopping mall", category: "shopping" },
  { name: "Gilly's Redefined", notes: "Restaurant", category: "restaurant" },
  { name: "Glen's Bakehouse", notes: "Bakery", category: "cafe" },
  { name: "HAL Heritage Centre", notes: "Aviation museum", category: "museum" },
  { name: "High Ultra Lounge", notes: "Same as 31st Floor?", category: "bar" },
  { name: "Indian Coffee House", notes: "Traditional coffee", category: "cafe" },
  { name: "ISKCON Temple", notes: "Temple", category: "temple" },
  { name: "Koshy's", notes: "Same as Koshys", category: "restaurant" },
  { name: "Lalbagh Botanical Garden", notes: "Botanical garden", category: "park" },
  { name: "Lavonne Cafe", notes: "Cafe and bakery", category: "cafe" },
  { name: "Loft 38", notes: "Rooftop bar", category: "bar" },
  { name: "Matteo Coffea", notes: "Coffee place", category: "cafe" },
  { name: "Meghana Foods", notes: "Biryani chain", category: "restaurant" },
  { name: "Monkey Bar", notes: "Gastropub", category: "bar" },
  { name: "MTR 1924", notes: "Traditional restaurant", category: "restaurant" },
  { name: "Museum of Art & Photography", notes: "MAP museum", category: "museum" },
  { name: "Nagarjuna", notes: "Andhra restaurant", category: "restaurant" },
  { name: "Nandhana Palace", notes: "Restaurant chain", category: "restaurant" },
  { name: "National Gallery of Modern Art", notes: "Art gallery", category: "museum" },
  { name: "Punjabi Rasoi", notes: "Punjabi restaurant", category: "restaurant" },
  { name: "Roastery Coffee House", notes: "Coffee place", category: "cafe" },
  { name: "Sankey Tank", notes: "Lake park", category: "park" },
  { name: "Shri Sagar (CTR)", notes: "Same as CTR", category: "restaurant" },
  { name: "Skyye Lounge", notes: "Rooftop lounge", category: "bar" },
  { name: "Sly Granny", notes: "Cafe", category: "cafe" },
  { name: "Soul Santé Cafe", notes: "Healthy cafe", category: "cafe" },
  { name: "South Thindies", notes: "South Indian breakfast", category: "restaurant" },
  { name: "The 13th Floor", notes: "Same as 13th Floor MG Road?", category: "bar" },
  { name: "The Fatty Bao", notes: "Asian restaurant", category: "asian" },
  { name: "The Hole in the Wall Cafe", notes: "Cafe", category: "cafe" },
  { name: "The Leela Palace", notes: "Hotel", category: "hotel" },
  { name: "The Oberoi", notes: "Hotel", category: "hotel" },
  { name: "The Only Place", notes: "Steakhouse", category: "restaurant" },
  { name: "Third Wave Coffee Roasters", notes: "Same as Third Wave Coffee", category: "cafe" },
  { name: "Toast & Tonic", notes: "Same as Toast and Tonic", category: "bar" },
  { name: "UB City Mall", notes: "Luxury mall", category: "shopping" },
  { name: "Ulsoor Lake", notes: "Lake", category: "park" },
  { name: "Vapour Pub & Brewery", notes: "Brewery", category: "bar" },
  { name: "Veena Stores", notes: "Breakfast place", category: "restaurant" },
  { name: "VV Puram Food Street", notes: "Food street", category: "street food" },
  { name: "Windmills Craftworks", notes: "Same as Windmills", category: "bar" },
  { name: "Yogisthaan Cafe", notes: "Yoga cafe", category: "cafe" }
]

console.log(`\n📝 New places to add to amit-real-visited-places.ts: ${NEW_APPROVED_PLACES.length}`)
console.log('\nThese places need to be properly formatted and added to your main list.')
console.log('Some may be duplicates with different names (e.g., CTR vs Shri Sagar)')