name: Debug Secrets

on:
  workflow_dispatch:

jobs:
  debug:
    runs-on: ubuntu-latest
    steps:
      - name: Debug Environment
        run: |
          echo "=== Debugging GitHub Secrets ==="
          echo "Repository: ${{ github.repository }}"
          echo "Actor: ${{ github.actor }}"
          echo ""
          echo "=== Checking Secret Availability ==="
          
          # Check if secrets are set (will show *** if they exist)
          echo "VERCEL_TOKEN exists: ${{ secrets.VERCEL_TOKEN != '' }}"
          echo "VERCEL_PROJECT_ID exists: ${{ secrets.VERCEL_PROJECT_ID != '' }}"
          echo "VERCEL_TEAM_ID exists: ${{ secrets.VERCEL_TEAM_ID != '' }}"
          
          # Check environment variables
          echo ""
          echo "=== Environment Variables ==="
          echo "VERCEL_TOKEN from env: ${VERCEL_TOKEN:+SET}"
          echo "PROJECT_ID from env: ${PROJECT_ID:+SET}"
          
          # Try direct secret access
          if [[ -n "${{ secrets.VERCEL_TOKEN }}" ]]; then
            echo "✅ VERCEL_TOKEN is accessible"
          else
            echo "❌ VERCEL_TOKEN is NOT accessible"
          fi
          
          if [[ -n "${{ secrets.VERCEL_PROJECT_ID }}" ]]; then
            echo "✅ VERCEL_PROJECT_ID is accessible"
          else
            echo "❌ VERCEL_PROJECT_ID is NOT accessible"
          fi
    env:
      VERCEL_TOKEN: ${{ secrets.VERCEL_TOKEN }}
      PROJECT_ID: ${{ secrets.VERCEL_PROJECT_ID }}